# Generated by Django 2.0.4 on 2018-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=200)),
                ('team_opr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_mscore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_opr_quantile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_mscore_quantile', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-team_opr_quantile'],
            },
        ),
        migrations.CreateModel(
            name='worldsTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('events', models.CharField(max_length=200)),
                ('ranks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wlts', models.CharField(max_length=200)),
                ('wpsps', models.CharField(max_length=200)),
                ('mscores', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oprs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
